Add support for new skeleton xml and 6dof xml
qualisys/RTClientSDK.Net pull request #10
Opened 2020-06-25 12:37 UTC by EmilRosenquist

## Add support for the new skeleton xml and 6dof xml. 

**Changes in 6dof settings**
\- Euler Names (Moved to general settings as Euler Angles)
**Per body:**
\+ MaximumResidual
\+ MinimumMarkersInBody
\+ BoneLengthTolerance
\+ Filter
\+ Mesh
\+ DataOrigin
\+ DataOrientation
**Per body point:**
\+ Name

2020-06-25 14:58 UTC, helmesjo approved these changes

2020-06-25 17:13 UTC, mlveggo approved these changes

2020-06-26 07:08 UTC, Henrik-Norgren commented on QTMSettings.cs
> +    public class Boundry
Boundary

2020-06-28 09:07 UTC, helmesjo requested changes
_Optionally:_ Set target framework version to 4.6.
Remove C# 7 features (`in` parameters).

2020-06-29 06:43 UTC, EmilRosenquist commented on QTMSettings.cs
> +    public class Boundry
Fixed

2020-06-29 11:56 UTC, helmesjo approved these changes

2020-06-29 12:02 UTC, merged